<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_oauth_server.server' shared service.

include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth2-php\\lib\\OAuth2.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth2-php\\lib\\IOAuth2Storage.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth2-php\\lib\\IOAuth2RefreshTokens.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth2-php\\lib\\IOAuth2GrantUser.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth2-php\\lib\\IOAuth2GrantCode.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth2-php\\lib\\IOAuth2GrantImplicit.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth2-php\\lib\\IOAuth2GrantClient.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth2-php\\lib\\IOAuth2GrantExtension.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\GrantExtensionDispatcherInterface.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\oauth-server-bundle\\Storage\\OAuthStorage.php';

return $this->privates['fos_oauth_server.server'] = new \OAuth2\OAuth2(new \FOS\OAuthServerBundle\Storage\OAuthStorage(($this->privates['fos_oauth_server.client_manager.default'] ?? $this->load('getFosOauthServer_ClientManager_DefaultService.php')), ($this->privates['fos_oauth_server.access_token_manager.default'] ?? $this->load('getFosOauthServer_AccessTokenManager_DefaultService.php')), ($this->privates['fos_oauth_server.refresh_token_manager.default'] ?? $this->load('getFosOauthServer_RefreshTokenManager_DefaultService.php')), ($this->privates['fos_oauth_server.auth_code_manager.default'] ?? $this->load('getFosOauthServer_AuthCodeManager_DefaultService.php')), ($this->privates['fos_user.user_provider.username'] ?? $this->load('getFosUser_UserProvider_UsernameService.php')), ($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php'))), $this->parameters['fos_oauth_server.server.options']);
